services:
  - type: web
    name: gold-jewelry-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FRONTEND_URL
        sync: false
