services:
  - type: web
    name: gold-jewelry-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    env: docker
    region: oregon
    healthCheckPath: /api/products
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FRONTEND_URL
        value: https://net-react-jewelry-product-catalog.vercel.app
      - key: PORT
        value: 8080
